version : '3'
services:
  db:
     image: postgres:11.15-alpine
     environment:
       - POSTGRES_PASSWORD=P2ssw0rd
     ports:
       - "5432:5432"
     volumes:
       - assetmanagement-pg-volume:/var/lib/postgresql/data
volumes:
  assetmanagement-pg-volume:
